# Generated by Django 2.2 on 2020-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateField()),
                ('billing_address', models.CharField(max_length=100)),
                ('total', models.IntegerField()),
                ('status', models.CharField(choices=[('Show All', 'SHOW ALL'), ('Order in process', 'ORDER IN PROCESS'), ('Shipped', 'SHIPPED'), ('Cancelled', 'CANCELLED')], default='Show All', max_length=6)),
            ],
        ),
    ]
