# Generated by Django 2.2.4 on 2020-07-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='card_type',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='city',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='credit_card_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='expiration_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='message',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='security_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='subject',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='zip_code',
            field=models.CharField(max_length=60),
        ),
    ]
