# Generated by Django 2.2 on 2020-04-29 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
