# Generated by Django 2.2.4 on 2020-07-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0003_auto_20200714_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
