# Generated by Django 2.2.4 on 2020-07-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0005_auto_20200714_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='expiration_date',
            field=models.CharField(max_length=8),
        ),
    ]
