# Generated by Django 2.2 on 2020-05-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0006_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='message',
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
