# Generated by Django 2.2 on 2020-05-01 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0007_auto_20200430_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='subject',
            new_name='shipping_address',
        ),
    ]
