# Generated by Django 2.2 on 2020-05-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0008_auto_20200430_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
