# Generated by Django 2.2 on 2020-05-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_app', '0009_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='user_id_creator',
            field=models.IntegerField(default=-1),
        ),
    ]
